📦 NEW: Domain App
RapidAPI/DevRel-Examples-External pull request #31
Opened 2021-12-17 14:37 UTC by ahmadbilaldev

This PR adds a [Domain Search App](https://rapidapi-example-domain-app.vercel.app/) built using a WHOIS API from RapidAPI Hub.

@ghoshnirmalya kindly take a look.

2021-12-19 07:31 UTC, ghoshnirmalya reviewed
I'm getting a 504 status code.

<img width="1677" alt="Screenshot 2021-12-19 at 12 59 58 PM" src="https://user-images.githubusercontent.com/6391763/146667331-982019cf-d47a-43b9-953d-d5b039788e8b.png">

2021-12-20 07:05 UTC, ahmadbilaldev commented
> I'm getting a 504 status code.

The API requires the domain name to be valid i.e., `godaddy.com` instead of just `godaddy`. I added error handling to inform the user about this.

2021-12-20 07:06 UTC, ghoshnirmalya requested changes
The form should submit even when enter is pressed.

2021-12-20 07:06 UTC, ghoshnirmalya commented on domain-app/pages/api/search.js
> +      console.error(error);
```suggestion
```

2021-12-20 13:39 UTC, ghoshnirmalya approved these changes

2021-12-20 13:39 UTC, merged