📦 NEW: News app
RapidAPI/DevRel-Examples-External pull request #4
Opened 2021-10-15 19:00 UTC by msaaddev

In this PR, I have included the source code of the `news-app` I built for an article. [Click here](https://rapidapi-example-news-app.vercel.app/) for a live preview.

@ghoshnirmalya kindly take a look.

2021-10-15 19:02 UTC, msaaddev commented
@ghoshnirmalya I have deployed my forked repo. I don't know why Vercel is giving this error.

2021-10-18 08:01 UTC, ghoshnirmalya commented on news-app/pages/index.js
> +          <Link href={news.url}>
There should be an anchor tag immediately after the Next.js `Link` component [unless the child is a functional component](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component).

2021-10-18 08:02 UTC, ghoshnirmalya commented on news-app/pages/index.js
> +          <Link href={news.url}>
For Lists or Arrays, you need to use [keys](https://reactjs.org/docs/lists-and-keys.html#keys).

2021-10-18 08:03 UTC, ghoshnirmalya commented on news-app/tailwind.config.js
> +      xl: { max: "1279px" },
Do we need to override these for our application?

2021-10-18 12:17 UTC, msaaddev commented
> > @ghoshnirmalya I have deployed my forked repo. I don't know why Vercel is giving this error.
> 
> Did you deploy on your own Vercel account?

Yes.

2021-10-20 16:02 UTC, msaaddev commented
> @msaaddev You can ignore the issue with the deployment. Would you mind working on this PR and getting it merged today?

Already working on it. 🙌🏻

2021-10-20 16:43 UTC, ghoshnirmalya requested changes

2021-10-20 16:43 UTC, ghoshnirmalya commented on news-app/pages/api/news.js
> +    console.log();
```suggestion
```

2021-10-20 16:43 UTC, ghoshnirmalya commented on news-app/tailwind.config.js
> +      xl: { max: "1279px" },
This issue is still not resolved.

2021-10-20 16:51 UTC, msaaddev commented
@ghoshnirmalya kindly take a look now.

2021-10-20 18:57 UTC, ghoshnirmalya approved these changes

2021-10-20 18:58 UTC, merged